- .gitignore
- bin/generate.py
- detections/cscript_via_cmd.yml
- detections/first_time_seen_cmd_line.yml
- detections/malicious_powershell_process_connect_to_internet_with_hidden_window.yml
- detections/malicious_powershell_process_encoded_command.yml
- detections/malicious_powershell_process_multiple_suspicious_arguments.yml
- detections/prohibited_apps_spawning_cmdprompt.yml
- detections/unusually_long_commandlines.yml
- detections/unusually_long_commandlines_mltk.yml
Updates to generate.py to output entities
updates to manifest files with entities
fixed flake8 errors
> updates to generate and manifests to support ASX

- .circleci/config.yml
fixed bug that dependabot is still working
> Circleci fix

- bin/generate.py
btool says invalid key "description" , commenting that key as a fix
> updating generate to comment out description in transforms

- bin/validate.py
The validate.py script was adapted in order to identify when the datamodel specified in data_metadata doesn't fit to the datamodel used in the search.
> CRL-1636 check datamodel metadata against used datamodel in search

- requirements.txt
Github alerted a security vuln for jinja2
updating requirements.txt with the fix
> update requirements.txt file

- package/default/data/ui/views/escu_summary.xml
- package/default/data/ui/views/explore_analytic_stories.xml
Fixed issue from CRL-1628. Removing data-toggle="tab" from some elements
> Remove `data-toggle="tab"`

- stories/suspicious_emails.yml
Added detection search to suspicious email story
> Added email brand monitoring to suspicious email story

- detections/malicious_powershell_process_execpolicy.yml
- investigations/get_process_file_activity.yml
- investigations/get_process_registry_activity.yml
- spec/v2/baselines.spec.json
- spec/v2/detections.spec.json
- spec/v2/investigations.spec.json
The check for executionpolicy bypass was too broad.
Also, added investigation searches for file and registry activity
while I was here
> Fixed issue in CRL-1387

- .circleci/config.yml
Remove extra var from old config left over.
> remove extra var

- detections/account_harvesting.yml
- detections/anomalous_webclick.yml
- detections/password_sharing.yml
Stream since the sourcetype in the search specifies Stream
> Removed data sources from fraud searches that were not Splunk

- investigations/dns_hijack_enrichment.yml
- investigations/get_certificate_for_domain.yml
- investigations/get_parent_process_info.yml
- investigations/investigate_user_activities_in_all_cloud_regions.yml
- investigations/investigate_user_activities_in_single_cloud_region.yml
- investigations/user_activity_via_cloudtrail.yml
A couple of investigative searches were using the 70m@m construct. But we need time offsets for these searches.
> Fixed time window errors.

- .circleci/config.yml
- README.md
- docs/splunk_docs_categories.wiki
- docs/stories_categories.md
- stories/samsam.yml
Fixing some errors we had earlier
> CI updates

- docs/README.md
Added a little more context up top. This page is now designed to be a portal that positions and provides links to our other apps.
> Updated README

- .circleci/config.yml
@patel-bhavin you found this one thank you!
> correcting release bug

- .circleci/config.yml
Update latest build on the the default attack range s3 bucket. Making sure latest release always is automatically updated in new attack range builds.
> Attack Range Update

- .circleci/config.yml
> fixing bug where CI crashed when publishing the package

- detections/activity_related_to_pass_the_hash.yml
- detections/remote_desktop_network_traffic.yml
- detections/remote_desktop_process_running_on_system.yml
- detections/schtasks_scheduling_job_on_remote_system.yml
- macros/detect_activity_related_to_pass_the_hash_attacks_filter.yml
- macros/remote_desktop_network_traffic_filter.yml
- macros/remote_desktop_process_running_on_system_filter.yml
- macros/schtasks_scheduling_job_on_remote_system_filter.yml
- stories/lateral_movement.yml
I tested and updated the detections for the lateral movement story and tested them with the Attack Range.
Changes:
- Update and improved the detection: Detect Activity Related to Pass the Hash Attacks
- Update the detection Remote Desktop Network Traffic
- Removed the detection Remote Registry Key Modification
- Update the detection Schtasks scheduling job on remote system
Detections:
- tested with Attack Range
- bumped the modification date and version
- add macros
- add mitre technique id
> CRL-1714 new version lateral movement

- detections/unload_sysmon_filter_driver.yaml
- detections/unload_sysmon_filter_driver.yml
- macros/unload_sysmon_filter_driver_filter.yml
- stories/disable_security_tools.yml
new search for "detecting unloading sysmon filter"
> CRL-1712 Disabling Security Tools

- investigations/investigate_cloud_compute_instance_activities.yml
- investigations/investigate_user_activities_in_all_cloud_regions.yml
- investigations/investigate_user_activities_in_single_cloud_region.yml
- macros/ec2_excessive_runinstances_mltk_input_filter.yml
- macros/ec2_excessive_terminateinstances_mltk_input_filter.yml
- macros/investigate_cloud_compute_instance_activities_output_filter.yml
- macros/investigate_user_activities_in_all_cloud_region_output_filter.yml
- macros/investigate_user_activities_in_single_cloud_region_output_filter.yml
- macros/previously_seen_cloud_compute_creations_by_user_input_filter.yml
- macros/previously_seen_cloud_compute_image_input_filter.yml
- macros/previously_seen_cloud_compute_instance_types_input_filter.yml
- macros/previously_seen_cloud_regions_input_filter.yml
> CRL-1717 - Added "search *" definitions to the macros without them… resolves #292

- detections/clients_connecting_to_multiple_dns_servers.yml
- detections/dns_record_changed.yml
- macros/clients_connecting_to_multiple_dns_servers.yml
- macros/dns_record_changed_filter.yml
macro definition added
macro naming convention: added "output" in the name
> adding definitions

- .dependabot/config.yml
use dependabot to automatically merge deps that pass CI
> automatically merge deps

- .dependabot/config.yml
> no need to specify path

- detections/aws_activity_in_new_region.yml
Reworked search string to use the right syntax for the macros .. did a basic test using data from Rishi.
> fixing issue #343

- .circleci/config.yml
> fixing issue with seans PR

- stories/credential_dumping.yml
- stories/disable_security_tools.yml
- stories/dns_hijacking.yml
- stories/lateral_movement.yml
- stories/windows_privilege_escalation.yml
Updating Mod dates and versions of stories that were updates in 1.0.49.
This addresses the issue reported by Monzy
> updating mod dates and version

- detections/dns_query_length_mltk.yml
- detections/dns_query_length_with_high_standard_deviation.yml
- macros/dns_query_length_mltk_filter.yml
- macros/dns_query_length_with_high_standard_deviation_filter.yml
attack range freezing on testing against attack ID T1071 so query is untested against atomic red team behavior for now
> Update version info and macros

- detections/ec2_instance_started_with_previously_unseen_instance_type.yml
another detection that had the wrong time convert command
> fixes issue 343

- detections/macos_re-opened_applications.yml
this is an update from PR: https://github.com/splunk/security-content/pull/353
> corrected a few bugs with the detection spec for jwindley-splunk/T1164

- bin/doc-gen.py
- docs/stories_categories.md
> Fix company and email fields in maintainer list in doc-gen.py

- detections/container_implant_aws_detection.yml
- detections/container_implant_gcp_detection.yml
- investigations/container_listing_aws_investigation.yml
- macros/container_implant_aws_detection_filter.yml
- macros/container_implant_gcp_detection_filter.yml
- stories/container_implant_story.yml
New container implantation detection, investigation story
> Container implantation

- detections/create_or_delete_network_shares.yml
We are proposing to use AND intead of OR, we have tested this in our environment.
> Create or delete windows shares using net.exe

- detections/email_files_not_in_outlook_directory.yml
> Changing .dll to .pst

- baselines/update_previously_seen_aws_users.yml
- stories/apache_struts.yml
- stories/ransomware.yml
reported in slack by Carlos Arroyo.
> fixing reported error with baseline update_previously_seen_aws_users

- detections/dns_record_changed.yml
- macros/dns_record_changed_filter.yml
just caught this doing some testing on ASX, matching it to the actual macro name :-)
> fixing a mispelled macro

- package/appserver/static/js/lib/tabs.js
base on: https://github.com/LukeMurphey/splunk-dashboard-tabs-example/blob/master/src/appserver/static/tabs.js
@LukeMurphey mentioned this was something he address in that build of the `tabs.js` file. I upgraded and tested with a splunk8 attack_range build and it seems to resolve the issue.
> updating tab.js for splunk 8 support

- detections/email_files_not_in_outlook_directory.yml
Filesystem.file_path!="C:\\Users\\*\\AppData\\Local\\Microsoft\\Outlook*"
> updating the file path for newer version of Windows

- detections/outlook_writing_zip.yml
search is tested, check the screenshot
> CRL-1730: adding dest to the search syntax

- detections/first_time_seen_cmd_line.yml
- macros/first_time_seen_cmd_line_filter.yml
Updating how to implement and macro ymls for clarity
> CRL-1733: updating instructions for better clarification

- spec/v2/detections.spec.json
added cloud as a security_domain enum values
> Issue -370 spec update for security domain

- detections/registry_privilege_escalation.yml
tested this using attack_range
> CRL-1736: search updated

- detections/okta_failed_sso_attempt.yml
- detections/okta_multiple_users_with_auth_failures_from_ip.yml
- detections/okta_user_lockouts.yml
- detections/okta_user_logins_from_multiple_cities.yml
- investigations/get_okta_activity_by_app.yml
- investigations/get_okta_activity_by_ip.yml
- investigations/get_okta_user_activity.yml
- macros/okta_failed_sso_attempt_filter.yml
- macros/okta_multiple_users_with_auth_failures_from_ip_filter.yml
- macros/okta_user_lockouts_filter.yml
- macros/okta_user_logins_from_multiple_cities_filter.yml
- spec/v2/baselines.spec.json
- spec/v2/detections.spec.json
- spec/v2/investigations.spec.json
- stories/okta_story.yml
- stories/suspicious_okta_activities.yml
Stlll needs work - do not merge yet
> new files for okta story

- .circleci/config.yml
increasing timeout in cricleCI to 45s. hoping this would resolve CI failing on link checking
> increasing timeout

- README.md
- package/appserver/static/analytic_story_details.js
points run story button to the ASX execute page with the story selected instead of github url looks sloppy.. 
When the app is not installed it displays the following error
> points run story button to the ASX app 

- README.md
updating links and instructions for asx in README
> MINOR FIX:  Readme liche bug

- detections/create_local_admin_via_net.yml
- stories/lateral_movement.yml
Changes Processs to Processes.
Moved process search to tstats.
> Fixed typo in search, search optimization

- .circleci/config.yml
- detections/abnormally_high_aws_instances_launched_by_user.yml
adds alerting logic to failed steps
> adding logic to alert on failed steps via slack

- detections/unsigned_image_loaded_by_LSASS.yml
found a bug from the conversion process
> bug in detection

- docs/README.md
- docs/splunk_docs_categories.wiki
- docs/stories_categories.md
- package/default/analytic_stories.conf
- package/default/analyticstories.conf
- package/default/use_case_library.conf
- stories/netsh_abuse.yml
tyring to trigger CI job for test-dead-links not sure if the updated url works from the CI perspective yet
> Broken url update

- .circleci/config.yml
yeah I blame this PR on @P4T12ICK 😂
> we can run this manually lets take it off CI, causes too much noise

- detections/creation_of_shadow_copy_with_wmic_and_powershell.yml
updated detection 
- Creation of Shadow Copy with wmic and powershell
> update detection for credential dumping

- bin/generate-actors-map.py
- bin/generate-coverage-map.py
> forgot to get rid of tdqm

- detections/aws_detect_attach_to_role_policy.yml
- detections/aws_detect_permanent_key_creation.yml
- detections/aws_detect_role_creation.yml
- detections/aws_detect_sts_assume_role_abuse.yml
- detections/aws_detect_sts_get_session_token_abuse.yml
New searches for detection of permanent and temporary token abuse, creation of new role and attaching to role policy.
> Awslmsearches

- detections/aws_detect_permanent_key_creation.yml
fixed another AWS search while createding data
> newfixawsdetectpkey

- tests/T1003_001.yml
- tests/T1003_002.yml
- tests/T1003_003.yml
- tests/T1021_001.yml
- tests/T1027.yml
- tests/T1047.yml
- tests/T1053_005.yml
- tests/T1070.001.yml
- tests/T1112.yml
- tests/T1136_001.yml
- tests/T1562_001.yml
- tests/T1574_009.yml
> updated test files

- bin/generate.py
- bin/jinja2_templates/es_investigations.j2
- detections/detect_computer_changed_with_anonymous_account.yml
- detections/detect_credential_dumping_through_lsass_access.yml
- detections/detect_mimikatz_using_loaded_images.yml
- detections/detect_zerologon_via_zeek.yml
- macros/detect_zerologon_via_zeek_filter.yml
- macros/zeek_rpc.yml
- stories/detect_zerologon_attack.yml
Adds a new story to address Zerologon and 2 new detentions:
> Detect Zerologon Attack CVE-2020-1472 Story and detections

- bin/jinja2_templates/workflow_actions.j2
> fix workbench panel

- package/default/authorize.conf
adding a new authorize.conf file : 
Updates in ticket: https://jira.splunk.com/browse/TR-205
> addding auth conf file

- detections/endpoint/first_time_seen_cmd_line___ssa.yml
- notebooks/unit_test_prohibited_apps_spawning_cmdprompt.ipynb
- tests/unit_detect_prohibited_applications_spawning_cmd_exe.yml
adding unit test for prohibited apps spawning cmdprompt ssa detection
> Unit test prohibited apps spawning cmdprompt

- notebooks/phishing_detection_unit_test.ipynb
> Adding _time to phishing detection tests
